version: '3.8'

services:
  web:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis:6379

  redis:
    image: redis:7.0-bullseye
    ports:
      - '6379:6379'
